baseurl = "http://trashbirdecology.github.io/ecologyinterviewprep"
languageCode = "en-us"
title = "Help! for Interview Prep in Ecology"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Practice Questions"
    url = "/questions/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/trashbirdecology"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/trashbirdecol"

[params]
    description = "A super simple webpage to host some tips and resources for interview preps, with emphasis on natural resources."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
